version: "2"    
services:
    tagor:
        build: ./tac_slim
        restart: always
        ports: 
            - 8042:8042
            - 4242:4242
        volumes:
            - /user/orthanc/orthanc-db:/var/lib/orthanc/db
        