Taggy: 
    image: postgres:9.4
    restart: always
    environment:
        - POSTGRES_USER=taggy
        - POSTGRES_PASSWORD=taggyDBK
    ports:
        - 5432:5432
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql